export const GET_TODOS = 'GET_TODOS'
export const ADD_TODOS = 'ADD_TODOS'
export const DELETE_TODOS = 'DELETE_TODOS'
export const UPDATE_TODOS = 'UPDATE_TODOS'

export const GET_USERS = 'GET_USERS'
export const GET_USERS_FAV = 'GET_USERS_FAV'
export const GET_USERS_SEARCH = 'GET_USERS_SEARCH'

export const GET_USERS_EPISODE = 'GET_USERS_EPISODE'
export const GET_USERS_EPISODE_DETAIL = 'GET_USERS_EPISODE_DETAIL'

export const GET_USERS_LOGIN = 'GET_USERS_LOGIN'
export const GET_USERS_REGISTER = 'GET_USERS_REGISTER'

export const GET_USERS_CREATION = 'GET_USERS_CREATION'
export const GET_USERS_CREATE = 'GET_USERS_CREATE'
export const GET_USERS_CREATE_DETAIL = 'GET_USERS_CREATE_DETAIL'
export const GET_USERS_PROFILE = 'GET_USERS_PROFILE'

export const GET_USERS_DATA_PROFILE = 'GET_USERS_DATA_PROFILE'

export const GET_USERS_MYFAVOURITE = 'GET_USERS_MYFAVOURITE'
export const GET_USERS_SRC_MYFAVOURITE = 'GET_USERS_SRC_MYFAVOURITE'

export const GET_USERS_MYFAVOURITE_INSERT = 'GET_USERS_MYFAVOURITE_INSERT'
export const GET_USERS_MYFAVOURITE_DELETE = 'GET_USERS_MYFAVOURITE_DELETE'

export const SAVE_USERS_DETAIL = 'SAVE_USERS_DETAIL'
export const SAVE_USERS_EPISODE = 'SAVE_USERS_EPISODE'
export const SAVE_USERS_WEBTOON = 'SAVE_USERS_WEBTOON'







