export const GET_USERS_LOGIN = 'GET_USERS_LOGIN'

export const GET_USERS_ROOM = 'GET_USERS_ROOM'
export const INSERT_USERS_ROOM = 'INSERT_USERS_ROOM'
export const UPDATE_USERS_ROOM = 'UPDATE_USERS_ROOM'

export const GET_USERS_CUSTOMER = 'GET_USERS_CUSTOMER'








